name: Publish Documentation to Github Pages 📘
on:
  push:
    branches:
      - main
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: ./.tool-versions
      - name: Setup Yarn
        uses: actions/cache@v6
        with:
          path: node_modules
          key: yarn-cache-${{ hashFiles('**/yarn.lock', '.yarnrc') }}
          restore-keys: yarn-cache-
      - run: yarn install --frozen-lockfile
      - name: Build docs
        run: yarn docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          commit_message: "docs: update"
          force_orphan: true
